---
- name: Install java 7 
  shell: brew cask install caskroom/versions/java7
  register: java7status

- name: Java 7 install result 
  debug: var=java7status.stderr

- name: Install latest java
  shell: brew cask install java
  register: javaLatestStatus

- name: Java 8 install result
  debug: var=javaLatestStatus.stderr

- name: Java install folder exists
  file: dest=/Library/Java/JavaVirtualMachines/ state=directory