---
- hosts: localhost
  connection: local
  vars:	
    home_directory: /Users/{{ ansible_user_id }}
    downloads_directory: /{{ home_directory }}/.ansible/downloads
  roles:
    # - ansible-download-directory
    # - google-chrome
    - iterm2
    - zsh
    # - intellij-idea
    - java
    - jenv